/** @format */

import { Button } from "@/components/ui/button";
import { cn } from "@repo/shared";
import { ArrowLeft } from "lucide-react";
import { parseAsBoolean, useQueryState } from "nuqs";
import { ChatRoomProvider } from "./chat-room-context";
import { ChatBox } from "./chatbox";
import { ChatsList } from "./chats-list";
import { useLocation, useNavigate } from "react-router";
import React from "react";
import {
	Crumbs,
	CrumbsLocationState,
	isStateWithCrumbs,
} from "@/routes/main/components/app-header/bread-crumb-navigation";
import { useChatDetails } from "./hooks/use-chat-details";
import { ChatDetails } from "./types";
import { useAuthStatus } from "@/hooks/use-auth-status-hook";
import { AllowedChatUserSchema } from "../../constants";
import { profileQueries } from "../../../profile/query-factory";
import { useQuery } from "@tanstack/react-query";
import { getDb } from "./db";

const useCorrectAutoCrumbs = () => {
	// if the bread crumbs were autogenerated from pathname, correct the last item label
	const currentLocation = useLocation();
	const navigate = useNavigate();
	const onCrumbsChange = React.useEffectEvent(
		(crumbsArr: Crumbs, chat: ChatDetails) => {
			const crumbs = [...crumbsArr];
			const lastCrumbIndex = crumbs.length - 1;
			const lastCrumb = crumbs[crumbs.length - 1];
			const hasAutogeneratedLabel =
				lastCrumb &&
				lastCrumb.label.trim().toLocaleLowerCase() === chat?.id;
			if (hasAutogeneratedLabel) {
				crumbs[lastCrumbIndex] = {
					...lastCrumb,
					label: `Chat with ${chat.recipient.name}`,
				};
				void navigate(currentLocation, {
					replace: true,
					// eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
					state: {
						...currentLocation.state,
						crumbs,
					} satisfies CrumbsLocationState,
				});
			}
		},
	);
	const { data: chatDetails } = useChatDetails();
	React.useEffect(() => {
		if (isStateWithCrumbs(currentLocation.state) && chatDetails) {
			onCrumbsChange(currentLocation.state.crumbs, chatDetails);
		}
	}, [chatDetails, currentLocation.state]);
};

const useInitChatDb = () => {
	const {
		cookies: { userType },
	} = useAuthStatus({
		assertAuthenticated: true,
		userTypesToAssert: AllowedChatUserSchema.options,
	});

	const { data: profile } = useQuery(profileQueries.byUserType(userType));

	React.useMemo(() => {
		if (profile?.id) {
			getDb(profile.id); // init db
		}
	}, [profile?.id]);

	// Recover stuck messages on page load
	React.useEffect(() => {
		if (!profile?.id) return;

		const recoverStuckMessages = async () => {
			const db = getDb(profile.id);

			// Use transaction to batch-update all SENDING → FAILED messages
			// This prevents multiple re-renders (single DB change event)
			await db.transaction("rw", db.messages, async () => {
				const chatIds = await db.getChatIds();

				for (const chatId of chatIds) {
					const messages = await db.getChatMessages(chatId);

					for (const msg of messages) {
						if (msg.status === "SENDING") {
							await db.updateMessageStatus(msg.id, "FAILED");
						}
					}
				}
			});
		};

		void recoverStuckMessages().catch(console.error);
	}, [profile?.id]);

	const isDbReady = !!profile?.id;

	return isDbReady;
};

export default function ChatRoute() {
	useCorrectAutoCrumbs();

	const [isListShown, setIsListShown] = useQueryState(
		"list",
		parseAsBoolean.withDefault(false),
	);

	const isDbReady = useInitChatDb();
	if (!isDbReady) {
		return null;
	}

	return (
		<ChatRoomProvider>
			<div className="flex size-full gap-8">
				{/* TODO: Add highlighting active chat in MessagesList */}
				<ChatsList
					className={cn(
						"lg:w-auto xl:w-[35%]",
						// on mobile, show when list is active
						isListShown ? "flex" : "hidden",
						// always show on desktop
						"lg:flex",
					)}
				/>

				<div
					className={cn(
						"flex flex-1 flex-col gap-2 lg:min-w-[50%]",
						// on mobile, hide when list is shown
						isListShown && "hidden",
						// always show on desktop
						"lg:flex",
					)}>
					<Button
						onClick={() => void setIsListShown(true)}
						variant={"ghost"}
						className="self-start lg:hidden">
						<ArrowLeft /> Chats
					</Button>
					<ChatBox className="flex-1" />
				</div>
			</div>
		</ChatRoomProvider>
	);
}
